version: '3'

services:
  api:
    tty: true
    stdin_open: true
    build: 
      context: .
      dockerfile: api-Dockerfile
    volumes:
      - ./api:/go
    environment:
      PORT: 8080
    ports:
      - 8080:8080
    command: go run src/api/server/main.go
    depends_on:
      - db
  app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: app-Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    depends_on:
      - api
    command: npm run serve
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
